// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	reservations "peduli-covid/businesses/reservations"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *Repository) FindAll(ctx context.Context) ([]reservations.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []reservations.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByHospitalID provides a mock function with given fields: ctx, hospitalID
func (_m *Repository) FindByHospitalID(ctx context.Context, hospitalID int) ([]reservations.Domain, error) {
	ret := _m.Called(ctx, hospitalID)

	var r0 []reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []reservations.Domain); ok {
		r0 = rf(ctx, hospitalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, hospitalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) FindByUserID(ctx context.Context, userID int) ([]reservations.Domain, error) {
	ret := _m.Called(ctx, userID)

	var r0 []reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []reservations.Domain); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int) (reservations.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) reservations.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(reservations.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, data
func (_m *Repository) Store(ctx context.Context, data *reservations.Domain) (reservations.Domain, error) {
	ret := _m.Called(ctx, data)

	var r0 reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) reservations.Domain); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(reservations.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reservations.Domain) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, data
func (_m *Repository) UpdateStatus(ctx context.Context, data *reservations.Domain) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
