// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	invoices "peduli-covid/businesses/invoices"

	mock "github.com/stretchr/testify/mock"

	reservations "peduli-covid/businesses/reservations"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// FindByAdminID provides a mock function with given fields: ctx, adminID
func (_m *Usecase) FindByAdminID(ctx context.Context, adminID int) ([]reservations.Domain, error) {
	ret := _m.Called(ctx, adminID)

	var r0 []reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []reservations.Domain); ok {
		r0 = rf(ctx, adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *Usecase) FindByUserID(ctx context.Context, userID int) ([]reservations.Domain, error) {
	ret := _m.Called(ctx, userID)

	var r0 []reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []reservations.Domain); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, data
func (_m *Usecase) Store(ctx context.Context, data *reservations.Domain) (invoices.Domain, error) {
	ret := _m.Called(ctx, data)

	var r0 invoices.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) invoices.Domain); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(invoices.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reservations.Domain) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, data
func (_m *Usecase) UpdateStatus(ctx context.Context, data *reservations.Domain) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusDone provides a mock function with given fields: ctx, data
func (_m *Usecase) UpdateStatusDone(ctx context.Context, data *reservations.Domain) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
