// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	roles "peduli-covid/businesses/roles"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id int) (roles.Domain, error) {
	ret := _m.Called(id)

	var r0 roles.Domain
	if rf, ok := ret.Get(0).(func(int) roles.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(roles.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
