// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	hospitals "peduli-covid/businesses/hospitals"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *Repository) FindAll(ctx context.Context) ([]hospitals.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []hospitals.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []hospitals.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hospitals.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCityID provides a mock function with given fields: ctx, cityID
func (_m *Repository) FindByCityID(ctx context.Context, cityID int) ([]hospitals.Domain, error) {
	ret := _m.Called(ctx, cityID)

	var r0 []hospitals.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []hospitals.Domain); ok {
		r0 = rf(ctx, cityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hospitals.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, cityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int) (hospitals.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 hospitals.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) hospitals.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(hospitals.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, data
func (_m *Repository) Store(ctx context.Context, data *hospitals.Domain) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *hospitals.Domain) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
