// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"
	rsbedcovid "peduli-covid/businesses/rsbedcovid"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetProvince provides a mock function with given fields: ctx
func (_m *Repository) GetProvince(ctx context.Context) (rsbedcovid.ProvinceDomain, error) {
	ret := _m.Called(ctx)

	var r0 rsbedcovid.ProvinceDomain
	if rf, ok := ret.Get(0).(func(context.Context) rsbedcovid.ProvinceDomain); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(rsbedcovid.ProvinceDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
